#!/bin/bash
# Remote task script generated by sentaurus_automation.py
TARGET_DIR="etchingWithPlasma"

LOG_DIR="logs"
TDR_DIR="tdrs"
mkdir -p "$TARGET_DIR/$LOG_DIR" "$TARGET_DIR/$TDR_DIR"

# Find all .cmd files in the specified directory
find "$TARGET_DIR" -type f -name "*.cmd" | while read -r cmdfile; do
    echo "[Remote] Running $cmdfile..."
    sprocess "$cmdfile"
    logfile="${cmdfile%.cmd}.log"
    if [ -f "$logfile" ]; then
        mv "$logfile" "$TARGET_DIR/$LOG_DIR/"
    fi
    
    base="$(basename "$cmdfile" .cmd)"
    for tdr in ${base}*.tdr; do
        if [ -f "$tdr" ]; then
            mv "$tdr" "$TARGET_DIR/$TDR_DIR/"
        fi
    done
done

echo "[Remote] Task completed."
